# Generated by Django 6.0.2 on 2026-02-09 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_address_user_locality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='locality',
            new_name='location',
        ),
    ]
